<div class="modal " id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title center" id="myModalLabel"> <i class="fa fa-keyboard-o"></i>     Greek Keyboard</h4>
			</div>
			<div class="modal-body">
				<div class="btn-group" role="group" aria-label="&#32;">
					<button type="button" class="btn btn-default" onclick="addText('&#884;')">	&#884;</button>
					<button type="button" class="btn btn-default"	onclick="addText('&#885;')" >		&#885;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#902;')" >		&#902;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#903;')" >		&#903;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#904;')" >		&#904;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#905;')" >		&#905;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#906;')" >		&#906;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#908;')" >		&#908;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#910;')" >		&#910;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#911;')" >		&#911;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#913;')" >		&#913;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#914;')" >		&#914;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#915;')" >		&#915;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#916;')" >		&#916;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#917;')" >		&#917;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#918;')" >		&#918;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#919;')" >		&#919;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#920;')" >		&#920;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#921;')" >		&#921;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#922;')" >		&#922;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#923;')" >		&#923;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#924;')" >		&#924;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#925;')" >		&#925;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#926;')" >		&#926;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#927;')" >		&#927;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#928;')" >		&#928;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#929;')" >		&#929;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#931;')" >		&#931;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#932;')" >		&#932;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#933;')" >		&#933;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#934;')" >		&#934;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#935;')" >		&#935;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#936;')" >		&#936;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#937;')" >		&#937;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#940;')" >		&#940;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#941;')" >		&#941;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#942;')" >		&#942;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#943;')" >		&#943;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#945;')" >		&#945;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#946;')" >		&#946;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#947;')" >		&#947;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#948;')" >		&#948;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#949;')" >		&#949;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#950;')" >		&#950;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#951;')" >		&#951;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#952;')" >		&#952;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#953;')" >		&#953;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#954;')" >		&#954;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#955;')" >		&#955;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#956;')" >		&#956;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#957;')" >		&#957;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#958;')" >		&#958;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#959;')" >		&#959;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#960;')" >		&#960;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#961;')" >		&#961;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#962;')" >		&#962;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#963;')" >		&#963;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#964;')" >		&#964;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#965;')" >		&#965;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#966;')" >		&#966;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#967;')" >		&#967;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#968;')" >		&#968;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#969;')" >		&#969;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#972;')" >		&#972;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#973;')" >		&#973;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#974;')" >		&#974;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#976;')" >		&#976;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#981;')" >		&#981;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#986;')" >		&#986;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#987;')" >		&#987;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#988;')" >		&#988;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#989;')" >		&#989;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#990;')" >		&#990;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#991;')" >		&#991;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#992;')" >		&#992;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#993;')" >		&#993;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#1008;')" >		&#1008;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7936;')" >		&#7936;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7937;')" >		&#7937;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7938;')" >		&#7938;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7939;')" >		&#7939;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7940;')" >		&#7940;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7941;')" >		&#7941;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7942;')" >		&#7942;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7943;')" >		&#7943;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7944;')" >		&#7944;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7945;')" >		&#7945;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7946;')" >		&#7946;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7947;')" >		&#7947;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7948;')" >		&#7948;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7949;')" >		&#7949;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7950;')" >		&#7950;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7951;')" >		&#7951;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7952;')" >		&#7952;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7953;')" >		&#7953;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7954;')" >		&#7954;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7955;')" >		&#7955;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7956;')" >		&#7956;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7957;')" >		&#7957;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7960;')" >		&#7960;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7961;')" >		&#7961;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7962;')" >		&#7962;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7963;')" >		&#7963;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7964;')" >		&#7964;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7965;')" >		&#7965;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7968;')" >		&#7968;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7969;')" >		&#7969;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7970;')" >		&#7970;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7971;')" >		&#7971;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7972;')" >		&#7972;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7973;')" >		&#7973;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7974;')" >		&#7974;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7975;')" >		&#7975;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7976;')" >		&#7976;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7977;')" >		&#7977;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7978;')" >		&#7978;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7979;')" >		&#7979;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7980;')" >		&#7980;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7981;')" >		&#7981;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7982;')" >		&#7982;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7983;')" >		&#7983;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7984;')" >		&#7984;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7985;')" >		&#7985;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7986;')" >		&#7986;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7987;')" >		&#7987;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7988;')" >		&#7988;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7989;')" >		&#7989;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7990;')" >		&#7990;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7991;')" >		&#7991;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7992;')" >		&#7992;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7993;')" >		&#7993;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7994;')" >		&#7994;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7995;')" >		&#7995;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7996;')" >		&#7996;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7997;')" >		&#7997;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7998;')" >		&#7998;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#7999;')" >		&#7999;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8000;')" >		&#8000;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8001;')" >		&#8001;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8002;')" >		&#8002;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8003;')" >		&#8003;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8004;')" >		&#8004;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8005;')" >		&#8005;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8008;')" >		&#8008;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8009;')" >		&#8009;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8010;')" >		&#8010;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8011;')" >		&#8011;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8012;')" >		&#8012;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8013;')" >		&#8013;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8016;')" >		&#8016;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8017;')" >		&#8017;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8018;')" >		&#8018;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8019;')" >		&#8019;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8020;')" >		&#8020;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8021;')" >		&#8021;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8022;')" >		&#8022;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8023;')" >		&#8023;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8025;')" >		&#8025;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8027;')" >		&#8027;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8029;')" >		&#8029;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8031;')" >		&#8031;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8032;')" >		&#8032;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8033;')" >		&#8033;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8034;')" >		&#8034;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8035;')" >		&#8035;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8036;')" >		&#8036;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8037;')" >		&#8037;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8038;')" >		&#8038;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8039;')" >		&#8039;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8040;')" >		&#8040;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8041;')" >		&#8041;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8042;')" >		&#8042;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8043;')" >		&#8043;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8044;')" >		&#8044;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8045;')" >		&#8045;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8046;')" >		&#8046;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8047;')" >		&#8047;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8048;')" >		&#8048;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8050;')" >		&#8050;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8052;')" >		&#8052;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8054;')" >		&#8054;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8056;')" >		&#8056;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8058;')" >		&#8058;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8060;')" >		&#8060;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8064;')" >		&#8064;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8065;')" >		&#8065;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8066;')" >		&#8066;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8067;')" >		&#8067;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8068;')" >		&#8068;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8069;')" >		&#8069;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8070;')" >		&#8070;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8071;')" >		&#8071;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8072;')" >		&#8072;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8073;')" >		&#8073;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8074;')" >		&#8074;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8075;')" >		&#8075;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8076;')" >		&#8076;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8077;')" >		&#8077;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8078;')" >		&#8078;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8079;')" >		&#8079;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8080;')" >		&#8080;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8081;')" >		&#8081;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8082;')" >		&#8082;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8083;')" >		&#8083;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8084;')" >		&#8084;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8085;')" >		&#8085;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8086;')" >		&#8086;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8087;')" >		&#8087;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8088;')" >		&#8088;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8089;')" >		&#8089;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8090;')" >		&#8090;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8091;')" >		&#8091;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8092;')" >		&#8092;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8093;')" >		&#8093;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8094;')" >		&#8094;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8095;')" >		&#8095;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8096;')" >		&#8096;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8097;')" >		&#8097;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8098;')" >		&#8098;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8099;')" >		&#8099;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8100;')" >		&#8100;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8101;')" >		&#8101;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8102;')" >		&#8102;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8103;')" >		&#8103;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8104;')" >		&#8104;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8105;')" >		&#8105;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8106;')" >		&#8106;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8107;')" >		&#8107;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8108;')" >		&#8108;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8109;')" >		&#8109;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8110;')" >		&#8110;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8111;')" >		&#8111;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8112;')" >		&#8112;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8113;')" >		&#8113;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8114;')" >		&#8114;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8115;')" >		&#8115;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8116;')" >		&#8116;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8118;')" >		&#8118;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8119;')" >		&#8119;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8120;')" >		&#8120;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8121;')" >		&#8121;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8122;')" >		&#8122;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8124;')" >		&#8124;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8130;')" >		&#8130;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8131;')" >		&#8131;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8132;')" >		&#8132;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8134;')" >		&#8134;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8135;')" >		&#8135;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8136;')" >		&#8136;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8138;')" >		&#8138;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8140;')" >		&#8140;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8144;')" >		&#8144;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8145;')" >		&#8145;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8146;')" >		&#8146;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8147;')" >		&#8147;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8150;')" >		&#8150;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8151;')" >		&#8151;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8152;')" >		&#8152;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8153;')" >		&#8153;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8154;')" >		&#8154;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8160;')" >		&#8160;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8161;')" >		&#8161;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8162;')" >		&#8162;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8163;')" >		&#8163;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8164;')" >		&#8164;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8165;')" >		&#8165;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8166;')" >		&#8166;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8167;')" >		&#8167;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8168;')" >		&#8168;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8169;')" >		&#8169;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8170;')" >		&#8170;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8172;')" >		&#8172;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8178;')" >		&#8178;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8179;')" >		&#8179;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8180;')" >		&#8180;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8182;')" >		&#8182;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8183;')" >		&#8183;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8184;')" >		&#8184;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8186;')" >		&#8186;	</button>
<button type="button" class="btn btn-default"	onclick="addText('&#8188;')" >		&#8188;	</button>
				</div>
			</div><!-- end of modal-body-->
		</div> <!-- end of modal-content-->
	</div><!-- end of modal-dialog-->
</div><!-- end of modal-->			